# Generated by Django 3.2.18 on 2023-05-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
